# Generated by Django 4.2.23 on 2025-07-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_topicmodel_rommodel_host_messagemodel_rommodel_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rommodel',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic-roms+', to='myapp.topicmodel'),
        ),
    ]
