# Generated by Django 4.2.23 on 2025-07-01 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_rommodel_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
