# Generated by Django 4.2.23 on 2025-07-04 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_alter_rommodel_options_alter_topicmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='rom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rommodel'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
