# Generated by Django 4.2.23 on 2025-07-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image-1.jpg', upload_to='profile_images'),
        ),
    ]
